Output assets/demo.gif
Set Theme "Catppuccin Mocha"
Set TypingSpeed 100ms
Set WindowBar Colorful
Set CursorBlink true
Set FontSize 25

Hide
Type "PS1='\[\e[1;38;2;137;180;250m\]$\[\e[0m\] '"
Enter
Type "clear"
Enter
Show

Sleep 500ms
Type "go run ."
Sleep 100ms
Enter
Sleep 1s

Type "set 3"
Sleep 100ms
Enter
Sleep 1s

Type "status"
Sleep 100ms
Enter
Sleep 1s

Type "set 1"
Sleep 100ms
Enter
Sleep 1s

Type "status"
Sleep 100ms
Enter
Sleep 1s

Type "set 5"
Sleep 100ms
Enter
Sleep 1s

Type "status"
Sleep 100ms
Enter
Sleep 1s

Type "exit"
Sleep 100ms
Enter
Sleep 5s
