Output "/tmp/dummy.mp4"
Set Theme "Catppuccin Mocha"
Set TypingSpeed 100ms
Set WindowBar Colorful
Set CursorBlink true
Set FontSize 21

Hide
Type "PS1='\[\e[1;38;2;137;180;250m\]$\[\e[0m\] '"
Enter
Type "clear"
Enter
Show

Type "go run ."
Sleep 1ms
Enter
Sleep 1ms

Type "set 3"
Sleep 1ms
Enter
Sleep 1ms

Type "status"
Sleep 1ms
Enter
Sleep 1ms

Type "exit"
Sleep 1ms
Enter
Screenshot assets/ss.png
